stages:
  - build
  - push
  - deploy
  - cleanup


build:
  stage: build
  image: docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo ${PROJECT_NAME}
  script:
    - ./cmd/prod.sh build
  only:
    - master
    - beta

push:
  stage: push
  image: registry.caffeina.co/open-source/docker-gitlab-ci:latest    
  script:
    # Env
    - printenv ${ENV_FILE} > ./.env
    # Deploy
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./cmd/prod.sh push
    # Cleanup
    - rm -rf ${DOCKER_CERT_PATH}
  only:
    - master
    - beta

deploy:
  stage: deploy
  image: registry.caffeina.co/open-source/docker-gitlab-ci:latest  
  variables: 
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: ./certs
  script:
    # Env
    - printenv ${ENV_FILE} > ./.env
    # Certs
    - mkdir -p ${DOCKER_CERT_PATH}
    - printenv ${DOCKER_MACHINE_CA} > ${DOCKER_CERT_PATH}/ca.pem
    - printenv ${DOCKER_CLIENT_CERT} > ${DOCKER_CERT_PATH}/cert.pem
    - printenv ${DOCKER_CLIENT_KEY} > ${DOCKER_CERT_PATH}/key.pem
    # Deploy
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f ${DC_FILE} pull
    - docker-compose -f ${DC_FILE} up -d --remove-orphans
    # Cleanup
    - rm -rf ${DOCKER_CERT_PATH}
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: "https://ghzmdr.tk"
  only:
    - master
    - beta

cleanup:
  stage: cleanup
  image: registry.caffeina.co/open-source/docker-gitlab-ci:latest  
  variables: 
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: ./certs
  script:
    # Env
    - printenv $(echo "${ENV_FILE") > ./.env
    # Certs
    - mkdir -p ${DOCKER_CERT_PATH}
    - printenv ${DOCKER_MACHINE_CA} > ${DOCKER_CERT_PATH}/ca.pem
    - printenv ${DOCKER_CLIENT_CERT} > ${DOCKER_CERT_PATH}/cert.pem
    - printenv ${DOCKER_CLIENT_KEY} > ${DOCKER_CERT_PATH}/key.pem
    # Cleanup docker
    - docker system prune --all --volumes -f
    # Cleanup
    - rm -rf ${DOCKER_CERT_PATH}
  when: manual
  only:
    - master
    - beta
