stages:
  - build
  - push
  - deploy
  - cleanup

variables:
  COMPOSE_PROJECT_NAME: ${PROJECT_NAME}_${CI_COMMIT_REF_NAME}

build:
  stage: build
  image: registry.caffeina.co/open-source/docker-gitlab-ci:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - printenv $(echo "${CI_COMMIT_REF_NAME}_APP_ENV") > ./.env
    - echo $CI_PROJECT_NAME
  script:
    - ./cmd/prod.sh build
  only:
    - master
    - beta

push:
  stage: push
  image: registry.caffeina.co/open-source/docker-gitlab-ci:latest
  variables:
    COMPOSE_PROJECT_NAME: ${PROJECT_NAME}_${CI_COMMIT_REF_NAME}
  script:
    # Env
    - printenv ${ENV_FILE} > ./.env
    # Deploy
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./cmd/prod.sh push
    # Cleanup
    - rm -rf ${DOCKER_CERT_PATH}
  only:
    - master
    - beta

deploy:
  stage: deploy
  image: registry.caffeina.co/open-source/docker-gitlab-ci:latest  
  script:
    # Env
    - printenv ${ENV_FILE} > ./.env
    # Certs
    - mkdir -p ${DOCKER_CERT_PATH}
    - printenv ${DOCKER_MACHINE_CA} > ${DOCKER_CERT_PATH}/ca.pem
    - printenv ${DOCKER_CLIENT_CERT} > ${DOCKER_CERT_PATH}/cert.pem
    - printenv ${DOCKER_CLIENT_KEY} > ${DOCKER_CERT_PATH}/key.pem
    # Deploy
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f ${DC_FILE} pull
    - docker-compose -f ${DC_FILE} up -d --remove-orphans
    # Cleanup
    - rm -rf ${DOCKER_CERT_PATH}
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: "https://ghzmdr.tk"
  only:
    - master
    - beta

cleanup:
  stage: cleanup
  image: registry.caffeina.co/open-source/docker-gitlab-ci:latest  
  script:
    # Env
    - printenv $(echo "${ENV_FILE") > ./.env
    # Certs
    - mkdir -p ${DOCKER_CERT_PATH}    
    - printenv ${DOCKER_MACHINE_CA} > ${DOCKER_CERT_PATH}/ca.pem
    - printenv ${DOCKER_CLIENT_CERT} > ${DOCKER_CERT_PATH}/cert.pem
    - printenv ${DOCKER_CLIENT_KEY} > ${DOCKER_CERT_PATH}/key.pem
    # Cleanup docker
    - docker system prune --all --volumes -f
    # Cleanup
    - rm -rf ${DOCKER_CERT_PATH}
  when: manual
  only:
    - master
    - beta
