version: '3.5'

services:
  mysql:
    image: '${REGISTRY_HOST}/${PROJECT_PATHNAME}/${GIT_REF}/mysql'
    build:
      context: './mysql'
      dockerfile: ./Dockerfile

  nginx:
    image: '${REGISTRY_HOST}/${PROJECT_PATHNAME}/${GIT_REF}/nginx'
    build:
      context: './nginx'
      dockerfile: ./Dockerfile

  wordpress:
    image: '${REGISTRY_HOST}/${PROJECT_PATHNAME}/${GIT_REF}/wordpress'
    build:
      context: './wordpress'
      dockerfile: ./Dockerfile